from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    PageBreak,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(
    report_text,
    chart_file,
    avg_score,
    question_scores,
    recommendation
):

    filename = "Interview_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    # ==========================
    # COVER PAGE
    # ==========================

    content.append(
        Paragraph(
            "AI-Powered Mock Interview Platform",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 15)
    )

    content.append(
        Paragraph(
            "Candidate Performance Report",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 30)
    )

    content.append(
        Paragraph(
            f"<b>Overall Interview Score:</b> {avg_score:.1f}/100",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 15)
    )

    content.append(
        Paragraph(
            f"<b>Hiring Recommendation:</b> {recommendation}",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 30)
    )

    # ==========================
    # PERFORMANCE CHART
    # ==========================

    content.append(
        Paragraph(
            "Question-wise Performance",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    content.append(
        Image(
            chart_file,
            width=450,
            height=280
        )
    )

    content.append(
        Spacer(1, 25)
    )

    # ==========================
    # SCORE TABLE
    # ==========================

    content.append(
        Paragraph(
            "Question-wise Score Breakdown",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    data = [["Question", "Score"]]

    for i, score in enumerate(question_scores):
        data.append(
            [f"Question {i+1}", f"{score:.1f}"]
        )

    table = Table(
        data,
        colWidths=[250, 150]
    )

    table.setStyle(
        TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BACKGROUND', (0,1), (-1,-1), colors.whitesmoke)
        ])
    )

    content.append(table)

    content.append(
        Spacer(1, 25)
    )

    # ==========================
    # AI EVALUATION REPORT
    # ==========================

    content.append(
        Paragraph(
            "AI Evaluation Report",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    for line in report_text.split("\n"):

        if line.strip():

            content.append(
                Paragraph(
                    line,
                    styles["BodyText"]
                )
            )

            content.append(
                Spacer(1, 5)
            )

    content.append(
        Spacer(1, 20)
    )

    # ==========================
    # LEARNING ROADMAP
    # ==========================

    content.append(
        Paragraph(
            "Recommended Learning Roadmap",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    content.append(
        Paragraph(
            """
            • Spring Boot <br/><br/>
            • Microservices <br/><br/>
            • Docker <br/><br/>
            • AWS Cloud <br/><br/>
            • Kafka / RabbitMQ <br/><br/>
            • System Design <br/><br/>
            • Scalable Backend Development
            """,
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    # ==========================
    # FINAL NOTE
    # ==========================

    content.append(
        Paragraph(
            "Generated by AI-Powered Mock Interview Platform",
            styles["Italic"]
        )
    )

    doc.build(content)

    return filename